- hosts: localhost

  tasks:
    - name: Get access token
      k8s_auth:
        username: kubeadmin
        password: XXX
        host: YYY:6443
        validate_certs: false
      register: k8s_auth_results

    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        name: gitlab
        repo_url: "https://charts.gitlab.io"

    - name: Deploy Gitlab CI Runner
      kubernetes.core.helm:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        name: gcr
        chart_ref: gitlab/gitlab-runner
        release_namespace: gcr
        create_namespace: true
