- name: main
  hosts: localhost

  tasks:
    - name: Spin crc cloud
      containers.podman.podman_container:
        name: crc-cloud
        image: quay.io/crcont/crc-cloud:v0.0.2
        detach: false
        rm: true
        state: started
        command:
          - create
          - aws
          - --project-name
          - "crc-ocp412"
          - --backed-url
          - "file:///workspace"
          - --output
          - "/workspace"
          - --aws-ami-id
          - "ami-019669c0960dbcf14"
          - --pullsecret-filepath
          - "/pullsecret/pull-secret.txt"
          - --key-filepath
          - "/workspace/id_ecdsa"
        volume:
          - "{{ lookup('ansible.builtin.env', 'PWD') }}:/workspace:z"
          - "{{ lookup('ansible.builtin.env', 'HOME') }}/Downloads/pull-secret.txt:/pullsecret/pull-secret.txt:z"
          - "{{ lookup('ansible.builtin.env', 'HOME') }}/.aws:/root/.aws:z"
      tags:
        - up

    - name: Get access token
      k8s_auth:
        username: kubeadmin
        password: "{{ lookup('file', '{{ playbook_dir }}/../password') }}"
        host: "https://api.{{ lookup('file', '{{ playbook_dir }}/../host') }}.nip.io:6443"
        validate_certs: false
      register: k8s_auth_results
      tags:
        - up

    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: gitlab
        repo_url: "https://charts.gitlab.io"
      tags:
        - up

    - name: Deploy Gitlab CI Runner
      kubernetes.core.helm:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        name: gcr
        chart_ref: gitlab/gitlab-runner
        release_namespace: gcr
        create_namespace: true
        host: "https://api.{{ lookup('file', '{{ playbook_dir }}/../host') }}.nip.io:6443"
      tags:
        - up

    - name: Tear down crc cloud
      containers.podman.podman_container:
        name: crc-cloud
        image: quay.io/crcont/crc-cloud:v0.0.2
        detach: false
        rm: true
        state: started
        command:
          - destroy
          - --project-name
          - "crc-ocp412"
          - --backed-url
          - "file:///workspace"
          - --provider
          - "aws"
        volume:
          - "{{ lookup('ansible.builtin.env', 'PWD') }}:/workspace:z"
          - "{{ lookup('ansible.builtin.env', 'HOME') }}/.aws:/root/.aws:z"
      tags: down
