apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: gitlab-ci-runner
  owner: platform-engineering

secretGenerator:
- name: gitlab-runner-secret
  envs:
    - .env
