name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      # - name: Run make up in dev container
      #   uses: devcontainers/ci@v0.3.1900000329
      #   with:
      #     runCmd: pwd
