name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      # - name: Run make up in dev container
      #   uses: devcontainers/ci@v0.3.1900000329
      #   with:
      #     runCmd: pwd
