name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run make up in dev container
        uses: devcontainers/ci@v0.3.1900000329
        with:
          runCmd: make infra && helm install --namespace default gitlab-runner --set gitlabUrl=${{ secrets.GITLAB_URL }},runnerRegistrationToken="${{ secrets.RUNNER_REGISTRATION_TOKEN }}" gitlab/gitlab-runner && make down 
