name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      # - name: Run make up in dev container
      #   uses: devcontainers/ci@v0.3.1900000329
      #   with:
      #     runCmd: pwd
